language: scala
scala:
- 2.11.11
- 2.12.3
jdk:
- oraclejdk8
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
script:
- gradle clean check
after_success:
- bash ./git-manage.sh
before_install:
- openssl aes-256-cbc -K $encrypted_61168456aa19_key -iv $encrypted_61168456aa19_iv
  -in deploy.key.enc -out deploy.key -d
- chmod 600 deploy.key
- eval `ssh-agent -s`
- ssh-add deploy.key